[workspace]
resolver = "3"
members = ["crates/httpboot"]

[workspace.dependencies]
anyhow = { version = "1.0.100", default-features = false }
log = "0.4.29"
uefi = { version = "0.36.1", default-features = false }
smoltcp = { version = "0.12.0", default-features = false }
